version: 2.1

setup: true

orbs:
  node: circleci/node@5.1.1

jobs:
  lint:
    working_directory: ~/project/src
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: yarn
      - node/install-packages:
          cache-path: ~/project/src/node_modules
          override-ci-command: yarn install
      - run: |
          yarn run compile-contracts
          yarn run lint
          yarn run check-contract
  test:
    working_directory: ~/project/src
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: yarn
      - node/install-packages:
          cache-path: ~/project/src/node_modules
          override-ci-command: yarn install
      - run: |
          yarn run compile-contracts
          yarn run tests
  publish:
    environment:
      IMAGE_NAME: ghcr.io/shutter-network/keyper-payer
    docker:
      - image: cimg/base:2023.12
    steps:
      - checkout
      - setup_remote_docker
      - run: DOCKER_BUILDKIT=1 docker build -t ${IMAGE_NAME}:sha-$(git rev-parse HEAD) .
      - run: echo ${GHCR_PAT} | docker login -u bilbeyt --password-stdin ghcr.io
      - run: docker push -a ${IMAGE_NAME}

workflows:
  app:
    jobs:
      - lint
      - test
      - publish:
          requires:
            - lint
            - test


