version: 2.1

setup: true

orbs:
  node: circleci/node@5.1.1

jobs:
  lint:
    working_directory: ~/project/src
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: yarn
      - node/install-packages:
          cache-path: ~/project/src/node_modules
          override-ci-command: yarn install
      - run: |
          yarn run compile-contracts
          yarn run lint
          yarn run check-contract
  test:
    working_directory: ~/project/src
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: yarn
      - node/install-packages:
          cache-path: ~/project/src/node_modules
          override-ci-command: yarn install
      - run: |
          yarn run compile-contracts
          yarn run tests
  publish:
    docker:
      - image: cimg/base:2023.12
    steps:
      - checkout
      - run: DOCKER_BUILDKIT=1 docker build -t keyper-payer:$(shell git describe --tags) -t keyper-payer:sha-$(shell git rev-parse HEAD) .
      - run: echo ${GHCR_PAT} | docker login -u bilbeyt --password-stdin ghcr.io
      - run: docker push -a keyper-payer

workflows:
  app:
    jobs:
      - lint
      - test
      - publish:
          filters:
            branches:
              only: main
            tags:
              only: /.*/


